name: arty
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.3 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: {args: ^2.3.1, dolumns: ^2.0.0, filesize: ^2.0.1, http: ^0.13.4, path: ^1.8.2}
